### ISSUE TITLE
SVG动态播放暂停按钮

### ISSUE THREAD

**Issue by upfain** [upfain/blog#11]
预览图

![2](https://user-images.githubusercontent.com/23690145/32649843-8211b2e2-c636-11e7-9e8c-51f043072ee4.gif)

`HTML` 代码
```html
<svg viewBox="0 0 100 100">
    <path d="" />
</svg>
<button id="play">Play</button>
<button id="pause">Pause</button>
```

`CSS` 样式
```css
svg {
    width: 100%;
    fill: none;
}
path {
    stroke-width: 0;
    fill: red;
    transition: d 0.2s ease-in-out;
}
```
需要更改的 `path` 
```javascript
let path = document.querySelector('path')
```
```javascript
//播放按钮路径
const playPath = `
    M 20 10 l 30 20 l 0 40 l -30 20 
    M 50 30 l 30 20 l 0 0 l -30 20 z
`
//暂停按钮路径
const pausePath = `
    M 20 10 l 20 0 l 0 80 l -20 0 
    M 60 10 l 20 0 l 0 80 l -20 0 z
`
```
播放
```javascript
document.querySelector('#play').onclick = () => path.setAttribute('d', playPath)
```
暂停
```javascript
document.querySelector('#pause').onclick = () => path.setAttribute('d', pausePath)
```
当改变 `SVG` 的 `d` 属性时 要保证 路径一样 地址可以不一样 才会出现动态的效果
> `transition` 属性用于改变 `SVG` 路径的时候过渡
---
