### ISSUE TITLE
CSS无序照片瀑布流

### ISSUE THREAD

**Issue by upfain** [upfain/blog#5]
预览图
![After formatting](images/preview.jpg)

我们的 `HTML` 结构 使用 `section` 标签作为一个容器 `div` 为每一项 `img` 是每个图片

```html
<section>
    <div>
        <img src="you-img.png">
    </div>
    <div>
        <img src="you-img.png">
    </div>
    <div>
        <img src="you-img.png">
    </div>
    <!-- more ... -->
</section>
```

设置 `CSS`

```css
/*使用flex布局采用多行的方式*/
section {
    display: flex;
    flex-wrap: wrap;
}
/*占满最后一个元素的位置 防止最后一行的图片过宽*/
section::after {
    content: '';
    flex-grow: 999;
}
/*图片之间的间距为2像素*/
section div {
    flex-grow: 1;
    margin: 2px;
}
/*图片采用适应的方式展示*/
section div img {
    height: 200px;
    object-fit: cover;
    min-width: 100%;
}
```
