### ISSUE TITLE
CSS Reset

### ISSUE THREAD

**Issue by upfain** [upfain/blog#6]
```css


*, *:before, *:after {
    box-sizing: border-box;
    -webkit-overflow-scrolling: touch;
    touch-action: manipulation;
}

html, body, div, span, object, iframe,
h1, h2, h3, h4, h5, h6, p, pre, cite, code,
del, em, img, strong, sub, sup, var, b, i,
dl, dt, dd, ol, ul, li, form, label, legend,
table, tbody, tfoot, thead, tr, th, td, canvas, details, figcaption,
footer, header, menu, nav, section, audio, video {
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    font-size: 100%;
    vertical-align: baseline;
    background: transparent;
}

html {
    -webkit-tap-highlight-color: transparent;
    -webkit-text-size-adjust: 100%;
}

body{
    color: #333;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    font-size: 14px;
}

h1, h2, h3, h4, h5, h6 {
    font-weight: normal;
}

a {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    vertical-align: baseline;
    background: transparent;
    color: inherit;
    text-decoration: none;
}

img {
    display: inline-block;
    border: medium none;
    vertical-align: top;
}

li {
    list-style-type: none;
}

table {
    border-collapse: collapse;
    border-spacing: 0;
}

input, select {
    vertical-align: middle;
}

p {
    word-wrap: break-word;
}

input, button {
    background-color: inherit;
    color: inherit;
    font: inherit;
    outline: none;
    border: none;
    -webkit-appearance: none;
}

.clear:after {
    display: block;
    content: "";
    clear: both;
}
```
