### ISSUE TITLE
SVG五边形网状图

### ISSUE THREAD

**Issue by upfain** [upfain/blog#7]
预览图
![cascade-flow preview](https://raw.githubusercontent.com/upfain/blog/develop/images/svg-network.png)

`HTML` 结构

```html
<svg viewBox="0 0 100 100">
    <!--最外层的边框-->
    <polygon points="25,90 10,40 50,10 90,40 75,90"/>
    <!--五条向内的边框-->
    <path  d="M 50 50 l 0 -40 M 50 50 l 40 -10 M 50 50 l 25 40 M 50 50 l -25 40 M 50 50 l -40 -10"/>
    <!--覆盖物-->
    <polygon class="cover"/>
</svg>
```

`CSS` 样式

```css
path{
    fill:transparent;
}
svg *{
    fill: transparent;
    stroke-width: .4;
    stroke: rgba(196, 194, 194, 0.8);
}
.cover{
    fill: rgba(237,237,237,.6);
    /*处理误差*/
    transform: translate(0,3px);
}
```

算出角的坐标

```javascript
function value(value, index, total) {
    var x = 0
    var y = - value * .8
    var angle = Math.PI * 2 / total * index
    var cos = Math.cos(angle)
    var sin = Math.sin(angle)
    var tx = x * cos - y * sin + 100
    var ty = x * sin + y * cos + 100
    return {
        x: tx / 2,
        y: ty / 2
    }
}
```
从内向外延伸五个角的长度  (0-100)
```javascript
var angle = [90,70,88,80,66]
```
拼接 `points`
```javascript
var points = ''
for(var i = 0 ; i < angle.length ; i++){
    var d = value(angle[i], i + 1, 5)
    points += d.x + "," + d.y + '&'
}
angle = points.split('&')
```
设置到 `polygon` 属性上
```javascript
var polygon = document.querySelector('.cover')
polygon.setAttribute("points", angle[0]+' '+angle[1]+' '+angle[2]+' '+angle[3]+' '+angle[4])
```

**Comment by upfain** [comment]
预览图
![cascade-flow preview](https://raw.githubusercontent.com/upfain/blog/develop/images/svg-network.png)

`HTML` 结构

```html
<svg viewBox="0 0 100 100">
    <!--最外层的边框-->
    <polygon points="25,90 10,40 50,10 90,40 75,90"/>
    <!--五条向内的边框-->
    <path  d="M 50 50 l 0 -40 M 50 50 l 40 -10 M 50 50 l 25 40 M 50 50 l -25 40 M 50 50 l -40 -10"/>
    <!--覆盖物-->
    <polygon class="cover"/>
</svg>
```

`CSS` 样式

```css
path{
    fill:transparent;
}
svg *{
    fill: transparent;
    stroke-width: .4;
    stroke: rgba(196, 194, 194, 0.8);
}
.cover{
    fill: rgba(237,237,237,.6);
    /*处理误差*/
    transform: translate(0,3px);
}
```

算出角的坐标

```javascript
function value(value, index, total) {
    var x = 0
    var y = - value * .8
    var angle = Math.PI * 2 / total * index
    var cos = Math.cos(angle)
    var sin = Math.sin(angle)
    var tx = x * cos - y * sin + 100
    var ty = x * sin + y * cos + 100
    return {
        x: tx / 2,
        y: ty / 2
    }
}
```
从内向外延伸五个角的长度  (0-100)
```javascript
var angle = [90,70,88,80,66]
```
拼接 `points`
```javascript
var points = ''
for(var i = 0 ; i < angle.length ; i++){
    var d = value(angle[i], i + 1, 5)
    points += d.x + "," + d.y + '&'
}
angle = points.split('&')
```
设置到 `polygon` 属性上
```javascript
var polygon = document.querySelector('.cover')
polygon.setAttribute("points", angle[0]+' '+angle[1]+' '+angle[2]+' '+angle[3]+' '+angle[4])
```
